achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"welcome", "words25", "words50", "words100", "words250", "words500", "words1000", "brainfreeze", "kerplode", "quikword", "quikwords25", "quikwords50", "quikwords100", "quikwords250", "quikwordbest5", "quikwordbest15", "quikwordbest30"},
	achievements = {
		{
			id = "welcome",
			name = "Welcome to Labsylle!",
			description = "Play the Tutorial pak.",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "words25",
			name = "Word Seeker",
			description = "Find 25 total words.",
			isSecret = false,
			progressMax = 25,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "words50",
			name = "Word Scout",
			description = "Find 50 total words.",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "words100",
			name = "Word Nerd",
			description = "Find 100 total words.",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "words250",
			name = "Word Warrior",
			description = "Find 250 total words.",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "words500",
			name = "Worth Your Weight In Words",
			description = "Find 500 total words.",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "words1000",
			name = "I Eat Dictionaries For A Living",
			description = "Find 1,000 total words.",
			isSecret = false,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "brainfreeze",
			name = "Brrrrr!",
			description = "Get a brainfreeze.",
			isSecret = false,
			progressMax = 1,
			scoreValue = 1,
		},
		{
			id = "kerplode",
			name = "Ashes To Ashes",
			description = "Kerplode a bombed word.",
			isSecret = false,
			progressMax = 1,
			scoreValue = 1,
		},
		{
			id = "quikword",
			name = "Quik On The Draw",
			description = "Play a game of Quik-Word.",
			isSecret = false,
			progressMax = 1,
			scoreValue = 1,
		},
		{
			id = "quikwords25",
			name = "Swap Meet",
			description = "Find 25 Quik-Words.",
			isSecret = false,
			progressMax = 25,
			scoreValue = 1,
		},
		{
			id = "quikwords50",
			name = "Hot Swapping",
			description = "Find 50 Quik-Words.",
			isSecret = false,
			progressMax = 50,
			scoreValue = 1,
		},
		{
			id = "quikwords100",
			name = "Four Syllable Force",
			description = "Find 100 Quik-Words.",
			isSecret = false,
			progressMax = 100,
			scoreValue = 1,
		},
		{
			id = "quikwords250",
			name = "Syllabic Smackdown",
			description = "Find 250 Quik-Words.",
			isSecret = false,
			progressMax = 250,
			scoreValue = 1,
		},
		{
			id = "quikwordbest5",
			name = "Fast Fingers",
			description = "Reach round 5 in Quik-Word.",
			isSecret = false,
			progressMax = 5,
			scoreValue = 1,
		},
		{
			id = "quikwordbest15",
			name = "Blazing Digits",
			description = "Reach round 15 in Quik-Word.",
			isSecret = false,
			progressMax = 15,
			scoreValue = 1,
		},
		{
			id = "quikwordbest30",
			name = "Lightning Bolts Shoot From My Fingertips",
			description = "Reach round 30 in Quik-Word.",
			isSecret = false,
			progressMax = 30,
			scoreValue = 1,
		},
	}
}